name    'seteam-splunk'
version '2.0.0'
source  'https://github.com/puppetlabs-seteam/puppet-module-splunk.git'
author  'puppetlabs-seteam'
license 'Apache License, Version 2.0'
summary 'Manage and deploy Splunk servers and forwarders'
description  'Module to assit in deploying splunk or configuring rsyslog to send messages to your splunk server'
project_page 'https://github.com/puppetlabs-seteam/puppet-module-splunk'

dependency 'nanliu/staging', '>= 0.3.1'
