name    'puppetlabs-splunk'
version '3.0.1-1'
source  'https://github.com/hyclak/puppetlabs-splunk.git'
author  'Puppet Labs'
license 'Apache License, Version 2.0'
summary 'Manage and deploy Splunk servers and forwarders'
description  'Module to assit in deploying or configuring splunk'
project_page 'https://github.com/puppetlabs/puppetlabs-splunk'

dependency 'nanliu/staging', '>= 0.3.1'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 2.4.0'
